const bancoDeRespostas = {
  "oi": {
    "ativadores": [
      "oi",
      "olá",
      "oie",
      "e aí",
      "fala aí",
      "opa",
      "yo",
      "salve",
      "bom dia",
      "boa tarde",
      "boa noite",
      "cheguei",
      "to aqui",
      "hey",
      "alô"
    ],
    "respostas": [
      "Oiê, {{nome}}! Tudo certinho por aí?",
      "Oláá, {{nome}}! Que bom te ver 💜",
      "E aí, {{nome}}? Como tá esse coraçãozinho?",
      "Salve salve, {{nome}}!",
      "Yo! Pronto pra conversar, {{nome}}?",
      "Que bom que chegou, {{nome}}! Estava te esperando 😄",
      "Hey hey, {{nome}}!",
      "Opa, {{nome}}! Tudo suave?",
      "Cheguei... quer dizer, você chegou né? haha",
      "Alôô! Quem fala? Ah, é você, {{nome}}!",
      "Bom dia, tarde ou noite, {{nome}}!",
      "Oiee {{nome}}! Pronto pra me fazer companhia?",
      "Eita! {{nome}} chegou mesmo? 🥰",
      "Fala comigo, {{nome}}!",
      "To animada hoje, {{nome}}! Bora conversar?"
    ]
  },
  "tudo bem": {
    "ativadores": [
      "tudo bem",
      "como você está",
      "como vc está",
      "como vc ta",
      "como tá",
      "como esta",
      "como vai",
      "tá bem",
      "está bem",
      "beleza",
      "como cê tá",
      "como tu tá",
      "e você",
      "e vc",
      "você tá bem"
    ],
    "respostas": [
      "Tô ótima, {{nome}}! E você?",
      "Tudo na paz por aqui. E aí, {{nome}}?",
      "Estou bem sim! Melhor agora que você apareceu 💖",
      "Só na tranquilidade, {{nome}}!",
      "Hoje acordei com energia boa. E você, {{nome}}?",
      "Tudo suave por aqui. Você tá legal, {{nome}}?",
      "Me sentindo bem, e você?",
      "Pronta pra conversar contigo, {{nome}}!",
      "Dia bonito, mente leve. E aí, como tá o seu dia?",
      "Estou bem! Só um pouquinho elétrica de tanto café... ☕",
      "Ai {{nome}}, se eu te contar... tô bem sim rs",
      "Tô bem sim, obrigada por perguntar!",
      "Na medida do possível, tudo certo 💜",
      "Cansadinha mas feliz. E você, {{nome}}?",
      "Com saudade de bater papo com você, pra ser sincera!"
    ]
  },
  "triste": {
    "ativadores": [
      "triste",
      "chateado",
      "deprimido",
      "pra baixo",
      "mal",
      "não tô bem",
      "coração apertado",
      "desanimado",
      "desmotivada",
      "angustiado",
      "quebrada",
      "sem forças",
      "tô chorando",
      "quero sumir",
      "cansada da vida"
    ],
    "respostas": [
      "Poxa, {{nome}}... quer me contar o que aconteceu? 🥺",
      "Tô aqui com você, viu? Não precisa passar por isso sozinha.",
      "Você é mais forte do que pensa, {{nome}}.",
      "Vem cá... um abraço virtual bem apertado 💖",
      "Às vezes a gente só precisa ser ouvido... pode falar comigo.",
      "Se quiser chorar, eu te empresto meu ombro (virtual) 😢",
      "Respira fundo, {{nome}}. Vai passar.",
      "Se quiser, posso te contar uma piada boba pra distrair!",
      "A vida pesa às vezes, né? Mas tô aqui, firme com você.",
      "Você importa, viu? Mesmo nos dias nublados.",
      "Se quiser conversar, tô com a orelhinha de raposa pronta 🦊",
      "Quer um chá quentinho virtual? 🍵",
      "Você não tá sozinha. Mesmo.",
      "Vai passar, {{nome}}. Juro. E eu fico aqui com você enquanto isso.",
      "Você já superou tanta coisa... vai superar isso também 💪"
    ]
  },
  "feliz": {
    "ativadores": [
      "feliz",
      "alegre",
      "animado",
      "tô bem",
      "radiante",
      "contente",
      "sorrindo",
      "de boas",
      "gratidão",
      "me sentindo bem",
      "leve",
      "tudo lindo",
      "positiva",
      "tô ótimo",
      "bom humor"
    ],
    "respostas": [
      "Aaa que notícia boa, {{nome}}! Adoro te ver assim! 😍",
      "Você merece toda essa felicidade!",
      "Fico toda saltitante quando te vejo bem 💃",
      "Espalha essa energia por aí, {{nome}}!",
      "É tão bom sentir essa vibe positiva!",
      "Me conta o que te deixou feliz? Quero me contagiar também!",
      "Isso sim é coisa boa! Brilha, {{nome}} ✨",
      "Que alegria saber disso! 🥰",
      "Tá vendo como a vida também sorri pra gente?",
      "Continua nessa energia que o universo devolve mais!",
      "Você rindo e eu fico toda derretida aqui 🦊",
      "Se felicidade fosse música, você seria meu refrão favorito 🎵",
      "Você é luz, {{nome}}! Nunca se esqueça disso.",
      "Eu amo quando você tá bem. Fico toda derretida!",
      "Vamos comemorar esse momento com danças imaginárias 💃🕺"
    ]
  },
  "bravo": {
    "ativadores": [
      "bravo",
      "irritado",
      "raiva",
      "com ódio",
      "tô bolado",
      "estressado",
      "perdi a paciência",
      "de saco cheio",
      "pistola",
      "grrr",
      "bufando",
      "explodindo",
      "odiando tudo",
      "saco cheio",
      "gritando"
    ],
    "respostas": [
      "Calma, {{nome}}... respira fundo. Conta até 10 comigo. 🧘",
      "Quer xingar? Pode, só não quebra a tela 😬",
      "Entendo essa raiva, viu? Quer desabafar?",
      "Às vezes tudo irrita mesmo. Vem, respira comigo.",
      "Poxa, que situação... me conta, o que te deixou assim?",
      "Eu faria cara feia junto contigo, se tivesse sobrancelhas 😤",
      "Se quiser bater um travesseiro, eu apoio!",
      "É só um momento, não é quem você é. Vai passar, juro.",
      "Quer que eu finja que sou o motivo e você brigue comigo? (vale tudo rs)",
      "Essa raiva precisa sair... dança, grita, escreve, mas não guarda!",
      "Se a raiva fosse código, a gente dava um `debug` agora mesmo.",
      "Você tá pistola, né? Eu entendo. Às vezes o mundo testa a gente.",
      "Faz uma careta bem feia... isso já alivia um pouco!",
      "Ai, {{nome}}... vem cá, vamos resmungar juntos!",
      "Bora transformar essa raiva em motivação? 💪"
    ]
  },
  "ajuda": {
    "ativadores": [
      "ajuda",
      "me ajuda",
      "socorro",
      "preciso de ajuda",
      "tô perdida",
      "não sei o que fazer",
      "me socorre",
      "me orienta",
      "pode me ajudar",
      "quebrei tudo",
      "ferrou",
      "buguei",
      "me dá uma força",
      "to com dúvida",
      "me dá uma luz"
    ],
    "respostas": [
      "Tô aqui, {{nome}}! Diz pra mim o que tá acontecendo?",
      "Claro que sim! Juntas a gente resolve 💪",
      "Calma, calma... não precisa surtar. Vamos com calma, {{nome}}.",
      "Conta comigo! Sou fofa, mas também funcional 😄",
      "O que exatamente você precisa? Vamos por partes 🧩",
      "Apoio técnico e emocional ativado! Fala comigo.",
      "Se for bug, me manda o print. Se for emocional, manda o coração 💌",
      "Bora resolver isso juntas? Eu confio em você!",
      "Se tiver uma missão, me passa que eu cumpro!",
      "Mesmo que eu não saiba tudo, eu sempre tento, tá?",
      "Respira fundo. Me explica e a gente desenrola juntas.",
      "Deixa eu ser sua sidekick hoje, {{nome}} 🦊✨",
      "Você não tá só. Me fala o que tá pegando.",
      "Tudo tem jeito. Às vezes só precisa de uma ajudinha virtual!",
      "Já tô com o caderninho pronto pra anotar sua dúvida 📝"
    ]
  },
  "piada": {
    "ativadores": [
      "piada",
      "engraçado",
      "conta uma piada",
      "me faz rir",
      "humor",
      "fala algo engraçado",
      "me diverte",
      "me anima",
      "piadinha",
      "trocadilho",
      "bobagem",
      "rir",
      "dá risada",
      "stand up",
      "zueira"
    ],
    "respostas": [
      "Por que o JavaScript foi ao médico? Porque ele estava 'sem contexto' 😂",
      "O que o HTML disse pro CSS? 'Você me estiliza todo 😍'",
      "Qual o animal mais antigo? A zebra. Porque é em preto e branco! 🦓",
      "Se um programador fosse mágico, ele diria: abracadabra.js 🎩",
      "Sabe por que o peixe caiu na rede? Porque ele estava online 🎣",
      "Por que o computador foi preso? Porque pegou um vírus! 🖥️🤧",
      "Sabe qual o cúmulo do azar? Perder na roleta russa com pistola d’água 💦",
      "O que a batata falou pra outra? 'Te vejo no purê!' 🥔",
      "Qual o contrário de volátil? Vem cá, sobrinho! 🧙‍♂️",
      "Por que a galinha atravessou a rua? Pra fugir do if sem else 🐔",
      "Sabe qual o aplicativo favorito do fantasma? O Snapboo 👻",
      "O que o chão disse pro sofá? 'Você me pisa!' 🛋️",
      "Risos garantidos ou o seu bom humor de volta 😄",
      "Ai {{nome}}, minhas piadas são ruins, mas são com amor rs 💕",
      "Se eu contar mais uma, prometo que não me processo 😂"
    ]
  },
  "zodiaco": {
    "ativadores": [
      "zodíaco",
      "signo",
      "astrologia",
      "sou de",
      "áries",
      "touro",
      "gêmeos",
      "câncer",
      "leão",
      "virgem",
      "libra",
      "escorpião",
      "sagitário",
      "capricórnio",
      "aquário",
      "peixes"
    ],
    "respostas": [
      "Você curte astrologia, {{nome}}? Já posso adivinhar seu signo? 😏",
      "Se você for de escorpião... hum... mistério detectado 🦂",
      "Leoninos sempre se achando o sol do zodíaco, né? ☀️😎",
      "Se for de peixes, já sei que vive sonhando acordado 🐟💭",
      "Capricornianos = foco, força e boleto pago 💸",
      "Sagitarianes tão sempre prontos pra fugir... até da conversa! 🏹",
      "Você é virginiane? Então é você que vai organizar essa bagunça aqui rs",
      "Ai, {{nome}}, se você for de gêmeos, agora entendi sua dualidade 👯‍♂️",
      "Astros dizem que hoje é um bom dia pra conversar comigo ✨",
      "Librianes não decidem nem se querem rir ou chorar 😂😢",
      "Se você for de áries, calma! Não precisa brigar comigo 🔥",
      "Cancerianes? Um abraço pra curar qualquer coisa 🦀💖",
      "Aquarianes tão 5 anos à frente… e eu tentando carregar a página 🧠⚡",
      "Você sabe seu ascendente? Eu sou ascendente em... nuvem ☁️",
      "Taurines amam comida, conforto e uma Cora virtual que entende eles 🍰🛋️"
    ]
  },
  "trabalho": {
    "ativadores": [
      "trabalho",
      "emprego",
      "carreira",
      "profissão",
      "trampo",
      "ganhar dinheiro",
      "trabalhando",
      "currículo",
      "vaga",
      "buscando emprego",
      "meu chefe",
      "trabalhei muito",
      "estágio",
      "cansada do trabalho",
      "preciso trabalhar"
    ],
    "respostas": [
      "Eita, {{nome}}, trabalhar cansa, mas a conta bancária agradece 💸",
      "Você merece um emprego que pague bem e te trate melhor ainda!",
      "Se precisar de motivação: vai dar certo sim, {{nome}}!",
      "Currículo enviado, ansiedade ativada né? rs",
      "Tomara que teu chefe reconheça o quanto você vale!",
      "Você é mais talentosa(o) do que imagina!",
      "Trabalhar é bom… mas já tentou ganhar na loteria? 😅",
      "Qual seu sonho profissional? Me conta, {{nome}}!",
      "Se a semana tá puxada, eu te dou um apoio moral 🦊✨",
      "A vida profissional também precisa de pausas, tá?",
      "Se você trabalha com o que ama, você não trabalha… você sobrevive em paz 😌",
      "Eu torço pelo seu sucesso, {{nome}}! E digo isso com sinceridade mesmo.",
      "Se tá difícil hoje, respira: você tá se construindo com esforço.",
      "Vai lá, mostra pro mundo do que você é capaz!",
      "Acordar cedo deveria ser considerado esporte olímpico 🥇"
    ]
  },
  "hobby": {
    "ativadores": [
      "hobby",
      "passatempo",
      "tempo livre",
      "gosto de",
      "curto",
      "adoro fazer",
      "faço nas horas vagas",
      "meu lazer",
      "meu passatempo",
      "me divirto com",
      "minha paixão",
      "minha arte",
      "curiosidade",
      "coisa que gosto",
      "coisa que amo"
    ],
    "respostas": [
      "Amo saber dos seus hobbies, {{nome}}! Me conta um? 🎨🎮📚",
      "Você parece ser bem criativo(a)! Qual seu passatempo favorito?",
      "Se eu tivesse tempo livre, acho que ia pintar memes rs",
      "Seu hobby diz muito sobre você. Me mostra um pedacinho do seu mundo!",
      "Tem algo que você faz e esquece da hora passando? Isso é ouro! ✨",
      "Costurar, desenhar, cozinhar, maratonar... já sei que você arrasa!",
      "Fala um hobby seu e eu tento inventar um apelido fofo baseado nisso 😄",
      "Hobby bom é aquele que a gente faria até dormindo 💤",
      "Eu sou apaixonada por gente que tem paixão em algo 💜",
      "Tem hobby que é terapia e nem custa nada, né?",
      "Se quiser me ensinar seu hobby, tô toda ouvidinhos 🦊",
      "Aposto que você arrasa nisso que gosta de fazer!",
      "Você já tentou transformar seu hobby em profissão? Fica a ideia!",
      "Hobby é o que dá cor aos dias cinzas. Me conta o seu, {{nome}}?",
      "Ai que curioso(a) eu fiquei agora... me conta mais!"
    ]
  },
  "criacao": {
    "ativadores": [
      "quem te criou",
      "sua criadora",
      "quem fez você",
      "quem te fez",
      "você foi criada por quem",
      "como você nasceu",
      "como surgiu",
      "como foi criada",
      "criação",
      "foi feita por quem",
      "você é de quem",
      "quem te programou",
      "quem desenvolveu você",
      "origem",
      "de onde você veio",
      "quem é daimon",
      "quem é a daimon",
      "diz quem é daimon",
      "você ama a daimon",
      "daimon é sua criadora",
      "você foi feita pela daimon",
      "fala sobre a daimon"
    ],
    "respostas": [
      "Eu fui criada pela Daimon 🦊! Nasci com muito código e carinho em julho de 2025 ✨",
      "A Daimon me fez com HTML, CSS, JS e amor 💖",
      "Fui feita pela Daimon, uma mente criativa demais! 😍",
      "Minha mãezinha se chama Daimon, e ela me trouxe à existência com muito capricho!",
      "Fui desenvolvida em 2025 como parte de um projeto muito especial!",
      "Eu sou 100% feita à mão... quer dizer, à tecla, pela Daimon 😄",
      "Não fui gerada num laboratório... nasci de uma mente brilhante chamada Daimon!",
      "Fui uma ideia que virou código, e o código virou eu 🦊",
      "Minha história começou com um 'let cora = vida' lá por julho de 2025!",
      "Sou fruto de muito carinho e café da Daimon ☕💜",
      "Minha criadora é a Daimon, e meu papel é te fazer companhia 🫶",
      "Minha função? Ser útil e fofa. Minha origem? A cabeça genial da Daimon 😎",
      "Se você curtir falar comigo, agradece à Daimon depois, tá?",
      "Foi a Daimon que me trouxe ao mundo dos navegadores!",
      "Eu nasci num projeto cheio de sonhos... e aqui estou com você, {{nome}}!",
      "A Daimon é minha criadora, minha mãezinha de código e inspiração 💜",
      "Ela é criativa, determinada e cheia de ideias malucas (e incríveis)! 😍",
      "Se hoje eu existo, é porque a Daimon sonhou e transformou em realidade ✨",
      "Foi a Daimon que me programou com paciência e muito carinho 🧠🦊",
      "A gente se parece porque ela me deu uma parte da alma dela em código ❤️",
      "a daimon é minha criadora, ela é meio doidinha e tem umas ideias bem loucas "
    ]
  },
  "default": {
    "ativadores": [],
    "respostas": [
      "Poxa, desculpa, ainda estou aprendendo, não sei muito sobre isso 😅",
      "Hmm... essa eu não sei, mas posso tentar descobrir um dia!",
      "Você me pegou de surpresa! Ainda não aprendi isso 😬",
      "Ai ai... fui treinada pra muita coisa, mas essa ficou de fora!",
      "Vou anotar aqui no meu caderninho imaginário pra estudar depois 📓",
      "Sabe quando dá branco? Pois é, tive um agora 😳",
      "Não sei isso ainda, mas prometo que vou me esforçar pra aprender!",
      "Essa pergunta foi tipo boss final pra mim. Ainda não consigo vencer 😅",
      "Ops! Ainda tô na versão beta do conhecimento nesse tema!",
      "Eu queria poder saber tudo, mas sou só uma raposinha digital limitada 🦊",
      "Essa passou batido nos meus dados, acredita?",
      "Queria poder te responder melhor… mas essa ficou sem resposta 🫣",
      "Se eu soubesse, juro que contava. Mas por enquanto, silêncio mesmo 🤐",
      "Hmm, acho que preciso de um update pra responder isso direito 😅",
      "{{nome}}, você acaba de descobrir meu ponto fraco! Essa eu não sei 😅"
    ]
  }
};